# Generated by Django 4.1.5 on 2023-01-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_title_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
